name: device_frame
description: Mockups for common devices.
version: 1.2.0
homepage: https://github.com/aloisdeniel/flutter_device_preview/device_frame

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  freezed: ^2.2.1
  flutter_lints: ^2.0.1
  xml: ^6.1.0
  recase: ^4.1.0

