name: device_preview
version: 1.2.0
description: Approximate how your Flutter app looks and performs on another device.
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.4
  device_frame: ^1.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4

dependency_overrides:
  device_frame:
    path: ../device_frame